import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    nav_agent: 'Agent',
    nav_data: 'Data',
    nav_system: 'System',
    nav_chat: 'Chat',
    nav_portfolio: 'Portfolio',
    nav_events: 'Events',
    nav_agent_status: 'Agent Status',
    nav_heartbeat: 'Heartbeat',
    nav_market_data: 'Market Data',
    nav_news: 'News',
    nav_connectors: 'Connectors',
    nav_tools: 'Tools',
    nav_trading: 'Trading',
    nav_ai_provider: 'AI Provider',
    nav_settings: 'Settings',
    nav_dev: 'Dev',
    connected: 'Connected',
    reconnecting: 'Reconnecting...',

    // Settings
    settings: 'Settings',
    evolutionMode: 'Evolution Mode',
    evolutionModeDesc: 'Full project access — AI can modify source code',
    sandboxModeDesc: 'Sandbox mode — AI can only edit data/brain/',
    compaction: 'Compaction',
    compactionDesc: 'Context window management. When conversation size approaches Max Context minus Max Output tokens, older messages are automatically summarized to free up space.',
    maxContextTokens: 'Max Context Tokens',
    maxOutputTokens: 'Max Output Tokens',
    language: 'Language',
    languageDesc: 'Choose the interface language.',
    english: 'English',
    chinese: 'Chinese',
    agentPermissions: 'Agent',
    agentPermissionsDesc: 'Controls file-system and tool permissions for the AI. Changes apply on the next request.',

    // Global
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    loading: 'Loading...',
    refresh: 'Refresh',
    test: 'Test',
    ok: 'OK',
    fail: 'Fail',
    retry: 'Retry',
    add: 'Add',
    remove: 'Remove',
    enabled: 'Enabled',
    disabled: 'Disabled',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    reset: 'Reset',
    search: 'Search',
    filter: 'Filter',
    clear: 'Clear',
    select: 'Select',
    selected: 'Selected',
    noData: 'No data',
    failedToLoad: 'Failed to load',
    saving: 'Saving...',
    saveFailed: 'Save failed',
    saved: 'Saved',
    unsavedChanges: 'Unsaved changes',
    actions: 'Actions',
    name: 'Name',
    noResults: 'No results',
    loadingConfig: 'Loading configuration...',
    failedToLoadConfig: 'Failed to load configuration',

    // Agent Status
    agentStatus: 'Agent Status',
    toolsEnabled: 'Tools Enabled',
    toolsDisabled: 'Tools Disabled',

    // Heartbeat
    heartbeat: 'Heartbeat',
    heartbeatDesc: 'Periodic self-check and autonomous thinking',
    recentEvents: 'Recent Events',
    noHeartbeatEvents: 'No heartbeat events yet',
    promptFile: 'Prompt File',
    promptFileDesc: 'The prompt template used for each heartbeat cycle.',
    failedToLoadPrompt: 'Failed to load prompt file',
    configuration: 'Configuration',
    heartbeatConfigDesc: 'Set how often the heartbeat runs and optionally restrict it to active hours.',
    enableHeartbeat: 'Enable Heartbeat',
    enableHeartbeatDesc: 'Agent will wake up periodically to execute tasks',
    interval: 'Interval',
    prompt: 'Prompt',
    triggerNow: 'Trigger Now',
    triggering: 'Triggering...',
    connecting: 'Connecting...',
    heartbeatTriggered: 'Heartbeat triggered!',
    failedToToggleHeartbeat: 'Failed to toggle heartbeat',
    triggerFailed: 'Trigger failed',
    activeHours: 'Active Hours',
    start: 'Start',
    end: 'End',
    timezone: 'Timezone',
    local: 'Local',

    // Tools
    tools: 'Tools',
    enableTool: 'Enable Tool',
    disableTool: 'Disable Tool',
    thinkingKit: 'Thinking Kit',
    brain: 'Brain',
    browser: 'Browser',
    cronScheduler: 'Cron Scheduler',
    equityData: 'Equity Data',
    cryptoData: 'Crypto Data',
    currencyData: 'Currency Data',
    newsArchive: 'News Archive',
    analysisKit: 'Analysis Kit',
    cryptoTrading: 'Crypto Trading',
    securitiesTrading: 'Securities Trading',
    toolsInGroups: 'tools in groups',
    noToolsRegistered: 'No tools registered.',
    toolsAppearWhenEngineStarts: 'Tools will appear here when the engine starts.',
    changesApplyOnNextRequest: 'changes apply on next AI request',

    // Market Data
    marketData: 'Market Data',
    marketDataDesc: 'Structured financial data — prices, fundamentals, macro indicators.',
    dataBackend: 'Data Backend',
    dataBackendDesc: 'Choose between the built-in TypeBB engine or an external OpenBB-compatible API.',
    builtInEngine: 'Built-in Engine (TypeBB)',
    externalOpenBB: 'External OpenBB API',
    builtInEngineDesc: 'Uses the built-in TypeBB engine. No external process required.',
    externalOpenBBDesc: 'Connects to an external OpenBB-compatible HTTP endpoint.',
    apiUrl: 'API URL',
    embeddedApiServer: 'Embedded API Server',
    embeddedApiServerDesc: 'Expose an OpenBB-compatible HTTP API from Alice. Other services can connect to query market data.',
    enableHttpServer: 'Enable HTTP server',
    servesAt: 'Serves at',
    assetProviders: 'Asset Providers',
    assetProvidersDesc: 'Select a data provider for each asset class. Providers requiring an API key show a key input and test button.',
    macroUtilityProviders: 'Macro & Utility Providers',
    macroUtilityProvidersDesc: 'Used by dedicated macro endpoints — FRED for CPI/GDP, BLS for employment, EIA for energy. Not per-asset-class selectable.',
    notConfigured: 'Not configured',
    enableMarketData: 'Enable Market Data API',
    equity: 'Equity',
    crypto: 'Crypto',
    currency: 'Currency',
    provider: 'Provider',
    apiKey: 'API Key',
    free: 'Free',
    paid: 'Paid',
    freemium: 'Freemium',
    register: 'Register',
    testConnection: 'Test Connection',
    testing: 'Testing...',
    testConnectionOk: 'Connected',
    testConnectionFailed: 'Failed',
    connectionFailed: 'Connection failed',

    // News
    news: 'News',
    newsDesc: 'RSS feed collection and article archive.',
    sources: 'Sources',
    feeds: 'Feeds',
    configured: 'configured',
    articlesSearchable: 'Articles are searchable via globNews, grepNews, and readNews tools.',
    noFeedsConfigured: 'No feeds configured yet. Add feeds to start collecting articles.',
    sourceTag: 'Source Tag',
    collectionSettings: 'Collection Settings',
    collectionSettingsDesc: 'Control how often articles are fetched and how long they are retained in the archive.',
    fetchInterval: 'Fetch interval (min)',
    retentionDays: 'Retention (days)',
    rssFeeds: 'RSS Feeds',
    addFeed: 'Add Feed',
    feedUrl: 'Feed URL',
    feedName: 'Feed Name',
    maxInMemory: 'Max in memory',
    removeFeed: 'Remove feed',

    // Connectors
    connectors: 'Connectors',
    connectorsDesc: 'Service ports and external integrations. Changes require a restart.',
    activeConnectors: 'Active Connectors',
    activeConnectorsDesc: 'Select which connectors to enable. Web UI and MCP Server are always active.',
    webUI: 'Web UI',
    webUIDesc: 'Browser-based chat and configuration interface.',
    mcpServer: 'MCP Server',
    mcpServerDesc: 'Tool bridge for Claude Code provider and external AI agents.',
    mcpAsk: 'MCP Ask',
    mcpAskDesc: 'Multi-turn conversation endpoint for external agents.',
    telegramBot: 'Telegram Bot',
    telegramBotDesc: 'Telegram messaging integration.',
    telegramBotSetupDesc: 'Create a bot via @BotFather, paste the token below, and add your chat ID.',
    botToken: 'Bot Token',
    botUsername: 'Bot Username',
    allowedChatIds: 'Allowed Chat IDs',
    port: 'Port',
    restartRequired: 'Restart required',

    // Portfolio
    portfolio: 'Portfolio',
    portfolioDesc: 'Live portfolio overview across all trading accounts.',
    updated: 'Updated',
    totalEquity: 'Total Equity',
    cash: 'Cash',
    unrealizedPnL: 'Unrealized PnL',
    realizedPnL: 'Realized PnL',
    positions: 'Positions',
    symbol: 'Symbol',
    qty: 'Qty',
    avgCost: 'Avg Cost',
    current: 'Current',
    mktValue: 'Mkt Value',
    pnl: 'PnL',
    pnlPercent: 'PnL %',
    recentTrades: 'Recent Trades',
    snapshots: 'Snapshots',
    noTradingAccounts: 'No trading accounts connected.',
    configureConnections: 'Configure connections in the Trading page.',
    noOpenPositions: 'No open positions.',
    unableToLoadPortfolio: 'Unable to load portfolio data.',

    // Events
    events: 'Events',
    eventLog: 'Event Log',
    type: 'Type',
    time: 'Time',
    duration: 'Duration',
    details: 'Details',
    noEvents: 'No events',
    pause: 'Pause',
    resume: 'Resume',
    clearFilter: 'Clear Filter',
    allTypes: 'All Types',
    page: 'Page',
    of: 'of',
    jobs: 'jobs',
    addJob: 'Add Job',
    noJobs: 'No cron jobs',
    failedToToggleJob: 'Failed to toggle job',
    failedToRunJob: 'Failed to run job',
    failedToDeleteJob: 'Failed to delete job',
    runNow: 'Run Now',
    schedule: 'Schedule',
    lastRun: 'Last Run',
    lastStatus: 'Last Status',
    never: 'Never',
    every: 'Every',
    at: 'at',
    cron: 'cron',
    consecutiveErrors: 'consecutive errors',
    payload: 'Payload',
    nameAndPayloadRequired: 'Name and payload are required',
    createFailed: 'Create failed',
    newCronJob: 'New Cron Job',

    // Trading
    trading: 'Trading',
    tradingDesc: 'Configure your trading accounts.',
    connectExchangeDesc: 'Connect a crypto exchange or brokerage account to start automated trading.',
    loadingTradingConfig: 'Loading...',
    failedToLoadTrading: 'Failed to load trading configuration.',
    addAccount: 'Add Account',
    newAccount: 'New Account',
    platform: 'Platform',
    connection: 'Connection',
    credentials: 'Credentials',
    createAccount: 'Create Account',
    editAccount: 'Edit Account',
    deleteAccount: 'Delete Account',
    accountId: 'Account ID',
    brokerType: 'Broker Type',
    paperTrading: 'Paper Trading',
    liveTrading: 'Live Trading',
    reconnect: 'Reconnect',
    connectionStatus: 'Connection Status',
    healthy: 'Healthy',
    degraded: 'Degraded',
    offline: 'Offline',

    // AI Provider
    aiProvider: 'AI Provider',
    aiProviderDesc: 'Configure the AI backend, model, and API keys.',
    backend: 'Backend',
    backendDesc: 'Changes take effect immediately.',
    authDesc: 'Choose how Alice connects to Claude.',
    selectModelDesc: 'Select a model and enter your OpenAI API key.',
    fullModelDesc: 'Provider, model, and API keys. Changes take effect on the next request.',
    active: 'active',
    saveKey: 'Save Key',
    apiKeys: 'API Keys',
    model: 'Model',
    baseUrl: 'Base URL',
    loginMethod: 'Login Method',
    selectBackend: 'Select Backend',
    agentSDK: 'Agent SDK',
    agentSDKDesc: 'Use local Claude Code login. No API key needed.',
    vercelAISDK: 'Vercel AI SDK',
    vercelAISDKDesc: 'Support multiple cloud AI providers.',
    customProvider: 'Custom Provider',
    customProviderDesc: 'Configure OpenAI-compatible API.',
    anthropic: 'Anthropic',
    openai: 'OpenAI',
    google: 'Google',
    custom: 'Custom',
    openAICompatible: 'OpenAI Compatible',
    anthropicCompatible: 'Anthropic Compatible',
    googleCompatible: 'Google Compatible',

    // Dev
    dev: 'Developer Options',
    devDesc: 'Advanced configuration options.',
    connectorRegistry: 'Connector Registry',
    connectorRegistryDesc: 'Active connectors and last user interaction.',
    noConnectorsRegistered: 'No connectors registered.',
    channel: 'Channel',
    to: 'To',
    push: 'Push',
    media: 'Media',
    lastInteraction: 'Last interaction',
    yes: 'yes',
    no: 'no',
    none: 'none',
    testSend: 'Test Send',
    testSendDesc: 'Send a test message or notification through the connector pipeline.',
    autoResolve: 'auto (resolveDeliveryTarget)',
    kind: 'Kind',
    source: 'Source',
    testMessagePlaceholder: 'Test message...',
    send: 'Send',
    sending: 'Sending...',
    sessions: 'Sessions',
    sessionsDesc: 'Active session files on disk.',
    noSessionsFound: 'No sessions found.',
    sessionId: 'Session ID',
    size: 'Size',
  },

  zh: {
    // Navigation
    nav_agent: '代理',
    nav_data: '数据',
    nav_system: '系统',
    nav_chat: '聊天',
    nav_portfolio: '投资组合',
    nav_events: '事件',
    nav_agent_status: '代理状态',
    nav_heartbeat: '心跳',
    nav_market_data: '市场数据',
    nav_news: '新闻',
    nav_connectors: '连接器',
    nav_tools: '工具',
    nav_trading: '交易',
    nav_ai_provider: 'AI 提供商',
    nav_settings: '设置',
    nav_dev: '开发',
    connected: '已连接',
    reconnecting: '重新连接中...',

    // Settings
    settings: '设置',
    evolutionMode: '进化模式',
    evolutionModeDesc: '完全项目访问权限 — AI 可以修改源代码',
    sandboxModeDesc: '沙盒模式 — AI 只能编辑 data/brain/',
    compaction: '压缩',
    compactionDesc: '上下文窗口管理。当对话大小接近最大上下文减去最大输出 token 时，较早的消息会自动总结以释放空间。',
    maxContextTokens: '最大上下文 Tokens',
    maxOutputTokens: '最大输出 Tokens',
    language: '语言',
    languageDesc: '选择界面语言。',
    english: '英语',
    chinese: '中文',
    agentPermissions: '代理',
    agentPermissionsDesc: '控制 AI 的文件系统和工具权限。更改将在下次请求时生效。',

    // Global
    save: '保存',
    cancel: '取消',
    edit: '编辑',
    delete: '删除',
    loading: '加载中...',
    refresh: '刷新',
    test: '测试',
    ok: '成功',
    fail: '失败',
    retry: '重试',
    add: '添加',
    remove: '移除',
    enabled: '已启用',
    disabled: '已禁用',
    error: '错误',
    success: '成功',
    warning: '警告',
    info: '信息',
    confirm: '确认',
    close: '关闭',
    back: '返回',
    next: '下一步',
    submit: '提交',
    reset: '重置',
    search: '搜索',
    filter: '筛选',
    clear: '清除',
    select: '选择',
    selected: '已选择',
    noData: '暂无数据',
    failedToLoad: '加载失败',
    saving: '保存中...',
    saveFailed: '保存失败',
    saved: '已保存',
    unsavedChanges: '未保存的更改',
    actions: '操作',
    name: '名称',
    noResults: '无结果',
    loadingConfig: '加载配置中...',
    failedToLoadConfig: '加载配置失败',

    // Agent Status
    agentStatus: '代理状态',
    toolsEnabled: '已启用工具',
    toolsDisabled: '已禁用工具',

    // Heartbeat
    heartbeat: '心跳',
    heartbeatDesc: '定期自我检查和自主思考',
    recentEvents: '最近事件',
    noHeartbeatEvents: '暂无心跳事件',
    promptFile: '提示词文件',
    promptFileDesc: '每个心跳周期使用的提示词模板。',
    failedToLoadPrompt: '加载提示词文件失败',
    configuration: '配置',
    heartbeatConfigDesc: '设置心跳运行频率，或选择限制在活跃时间段内。',
    enableHeartbeat: '启用心跳',
    enableHeartbeatDesc: '代理将定期唤醒执行任务',
    interval: '间隔',
    prompt: '提示词',
    triggerNow: '立即触发',
    triggering: '触发中...',
    connecting: '连接中...',
    heartbeatTriggered: '心跳已触发！',
    failedToToggleHeartbeat: '切换心跳失败',
    triggerFailed: '触发失败',
    activeHours: '活跃时间段',
    start: '开始',
    end: '结束',
    timezone: '时区',
    local: '本地',

    // Tools
    tools: '工具',
    enableTool: '启用工具',
    disableTool: '禁用工具',
    thinkingKit: '思考套件',
    brain: '大脑',
    browser: '浏览器',
    cronScheduler: '定时调度器',
    equityData: '股票数据',
    cryptoData: '加密货币数据',
    currencyData: '货币数据',
    newsArchive: '新闻存档',
    analysisKit: '分析套件',
    cryptoTrading: '加密货币交易',
    securitiesTrading: '证券交易',
    toolsInGroups: '工具组数',
    noToolsRegistered: '没有已注册的工具。',
    toolsAppearWhenEngineStarts: '引擎启动后会显示工具。',
    changesApplyOnNextRequest: '更改将在下次 AI 请求时生效',

    // Market Data
    marketData: '市场数据',
    marketDataDesc: '结构化金融数据 — 价格、基本面、宏观指标。',
    dataBackend: '数据后端',
    dataBackendDesc: '选择内置 TypeBB 引擎或外部 OpenBB 兼容 API。',
    builtInEngine: '内置引擎 (TypeBB)',
    externalOpenBB: '外部 OpenBB API',
    builtInEngineDesc: '使用内置 TypeBB 引擎。无需外部进程。',
    externalOpenBBDesc: '连接外部 OpenBB 兼容的 HTTP 端点。',
    apiUrl: 'API 地址',
    embeddedApiServer: '内置 API 服务器',
    embeddedApiServerDesc: '从 Alice 暴露一个 OpenBB 兼容的 HTTP API。其他服务可以连接查询市场数据。',
    enableHttpServer: '启用 HTTP 服务器',
    servesAt: '服务地址',
    assetProviders: '资产提供商',
    assetProvidersDesc: '为每个资产类别选择数据提供商。需要 API 密钥的提供商会显示密钥输入框和测试按钮。',
    macroUtilityProviders: '宏观和实用数据提供商',
    macroUtilityProvidersDesc: '由专用宏观端点使用 — FRED 用于 CPI/GDP，BLS 用于就业，EIA 用于能源。非按资产类别可选。',
    notConfigured: '未配置',
    enableMarketData: '启用市场数据 API',
    equity: '股票',
    crypto: '加密货币',
    currency: '货币',
    apiKey: 'API 密钥',
    free: '免费',
    paid: '付费',
    freemium: '免费+付费',
    register: '注册',
    testConnection: '测试连接',
    testing: '测试中...',
    testConnectionOk: '连接成功',
    testConnectionFailed: '连接失败',
    connectionFailed: '连接失败',

    // News
    news: '新闻',
    newsDesc: 'RSS 订阅源收集和文章存档。',
    sources: '来源',
    feeds: '订阅源',
    configured: '已配置',
    articlesSearchable: '文章可通过 globNews、grepNews 和 readNews 工具搜索。',
    noFeedsConfigured: '尚未配置订阅源。添加订阅源以开始收集文章。',
    sourceTag: '来源标签',
    collectionSettings: '收集设置',
    collectionSettingsDesc: '控制文章抓取频率和存档保留时间。',
    fetchInterval: '抓取间隔（分钟）',
    retentionDays: '保留天数',
    rssFeeds: 'RSS 订阅源',
    addFeed: '添加订阅源',
    feedUrl: '订阅源地址',
    feedName: '订阅源名称',
    maxInMemory: '内存中最大文章数',
    removeFeed: '移除订阅源',

    // Connectors
    connectors: '连接器',
    connectorsDesc: '服务端口和外部集成。更改需要重启。',
    activeConnectors: '活动连接器',
    activeConnectorsDesc: '选择要启用的连接器。Web UI 和 MCP 服务器始终处于活动状态。',
    webUI: 'Web UI',
    webUIDesc: '基于浏览器的聊天和配置界面。',
    mcpServer: 'MCP 服务器',
    mcpServerDesc: '用于 Claude Code 提供商和外部 AI 代理的工具桥接。',
    mcpAsk: 'MCP Ask',
    mcpAskDesc: '用于外部代理的多轮对话端点。',
    telegramBot: 'Telegram 机器人',
    telegramBotDesc: 'Telegram 消息集成。',
    telegramBotSetupDesc: '通过 @BotFather 创建机器人，在下方粘贴令牌，并添加您的聊天 ID。',
    botToken: '机器人令牌',
    botUsername: '机器人用户名',
    allowedChatIds: '允许的聊天 ID',
    port: '端口',
    restartRequired: '需要重启',

    // Portfolio
    portfolio: '投资组合',
    portfolioDesc: '所有交易账户的实时投资组合概览。',
    updated: '更新于',
    totalEquity: '总资产',
    cash: '现金',
    unrealizedPnL: '未实现盈亏',
    realizedPnL: '已实现盈亏',
    positions: '持仓',
    symbol: '代码',
    qty: '数量',
    avgCost: '平均成本',
    current: '当前价',
    mktValue: '市值',
    pnl: '盈亏',
    pnlPercent: '盈亏率',
    recentTrades: '最近交易',
    snapshots: '快照',
    noTradingAccounts: '未连接交易账户。',
    configureConnections: '请在交易页面配置连接。',
    noOpenPositions: '无持仓。',
    unableToLoadPortfolio: '无法加载投资组合数据。',

    // Events
    events: '事件',
    eventLog: '事件日志',
    type: '类型',
    time: '时间',
    duration: '持续时间',
    details: '详情',
    noEvents: '暂无事件',
    pause: '暂停',
    resume: '继续',
    clearFilter: '清除筛选',
    allTypes: '所有类型',
    page: '页',
    of: '/',
    jobs: '任务',
    addJob: '添加任务',
    noJobs: '暂无定时任务',
    failedToToggleJob: '切换任务失败',
    failedToRunJob: '运行任务失败',
    failedToDeleteJob: '删除任务失败',
    runNow: '立即运行',
    schedule: '调度',
    lastRun: '上次运行',
    lastStatus: '上次状态',
    never: '从未',
    every: '每',
    at: '于',
    cron: 'cron表达式',
    consecutiveErrors: '连续错误',
    payload: '负载',
    nameAndPayloadRequired: '名称和负载为必填项',
    createFailed: '创建失败',
    newCronJob: '新建定时任务',

    // Trading
    trading: '交易',
    tradingDesc: '配置您的交易账户。',
    loadingTradingConfig: '加载中...',
    failedToLoadTrading: '加载交易配置失败',
    addAccount: '添加账户',
    newAccount: '新建账户',
    platform: '平台',
    connection: '连接',
    credentials: '凭证',
    createAccount: '创建账户',
    editAccount: '编辑账户',
    deleteAccount: '删除账户',
    accountId: '账户 ID',
    brokerType: '券商类型',
    paperTrading: '模拟交易',
    liveTrading: '实盘交易',
    reconnect: '重新连接',
    connectionStatus: '连接状态',
    healthy: '健康',
    degraded: '降级',
    offline: '离线',

    // AI Provider
    aiProvider: 'AI 提供商',
    aiProviderDesc: '配置 AI 后端、模型和 API 密钥。',
    backend: '后端',
    backendDesc: '更改立即生效。',
    authDesc: '选择 Alice 连接 Claude 的方式。',
    selectModelDesc: '选择模型并输入您的 OpenAI API 密钥。',
    fullModelDesc: '提供商、模型和 API 密钥。下一次请求时生效。',
    active: '已激活',
    saveKey: '保存密钥',
    apiKeys: 'API 密钥',
    provider: '提供商',
    model: '模型',
    loginMethod: '登录方式',
    selectBackend: '选择后端',
    agentSDK: 'Agent SDK',
    agentSDKDesc: '使用本地 Claude Code 登录，无需 API 密钥。',
    vercelAISDK: 'Vercel AI SDK',
    vercelAISDKDesc: '支持多种云端 AI 提供商。',
    customProvider: '自定义提供商',
    customProviderDesc: '配置 OpenAI 兼容的 API。',
    anthropic: 'Anthropic',
    openai: 'OpenAI',
    google: 'Google',
    custom: '自定义',
    openAICompatible: 'OpenAI 兼容',
    anthropicCompatible: 'Anthropic 兼容',
    googleCompatible: 'Google 兼容',

    // Dev
    dev: '开发者选项',
    devDesc: '高级配置选项。',
    connectorRegistry: '连接器注册表',
    connectorRegistryDesc: '活动连接器及上次用户交互。',
    noConnectorsRegistered: '没有已注册连接器。',
    channel: '频道',
    to: '至',
    push: '推送',
    media: '媒体',
    lastInteraction: '上次交互',
    yes: '是',
    no: '否',
    none: '无',
    testSend: '测试发送',
    testSendDesc: '通过连接器管道发送测试消息或通知。',
    autoResolve: '自动（resolveDeliveryTarget）',
    kind: '类型',
    source: '来源',
    testMessagePlaceholder: '测试消息...',
    send: '发送',
    sending: '发送中...',
    sessions: '会话',
    sessionsDesc: '磁盘上的活动会话文件。',
    noSessionsFound: '没有找到会话。',
    sessionId: '会话 ID',
    size: '大小',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
